/**
 * Utility functions for Output component
 * Extracted for better testability
 */

import type { PaletteConfig, Mode } from '~/types';
import { createDisplayColor } from './createDisplayColor';

export const generateSemanticColors = (palettes: PaletteConfig[], theme: 'light' | 'dark' | 'auto', currentMode: Mode): string => {
  if (!palettes || palettes.length === 0) {
    console.log('⚠️ No palettes for semantic colors');
    return '';
  }

  const palette = palettes[0]; // Используем первую палитру как основу
  if (!palette) {
    console.log('⚠️ No palette found for semantic colors');
    return '';
  }

  const shades = palette.swatches.reduce((acc, swatch) => {
    if (![0, 1000].includes(swatch.stop)) {
      acc[swatch.stop] = createDisplayColor(swatch.hex, currentMode, true);
    }
    return acc;
  }, {} as Record<number, string>);

  // Определяем цвета в зависимости от темы
  const isDark = theme === 'dark';
  const primaryBase = shades[500] || shades[600] || shades[700] || '#4f46e5';
  const primaryHover = shades[600] || shades[700] || shades[800] || '#4338ca';
  const primaryActive = shades[700] || shades[800] || shades[900] || '#3730a3';

  const semanticColors = {
    // Базовые цвета
    background: isDark ? '#0f172a' : '#ffffff',
    surface: isDark ? '#1e293b' : '#f8fafc',
    'surface-hover': isDark ? '#334155' : '#f1f5f9',
    border: isDark ? '#334155' : '#e2e8f0',
    'border-hover': isDark ? '#475569' : '#cbd5e1',

    // Текст
    'text-primary': isDark ? '#f8fafc' : '#0f172a',
    'text-secondary': isDark ? '#94a3b8' : '#475569',
    'text-tertiary': isDark ? '#64748b' : '#64748b',
    'text-disabled': isDark ? '#475569' : '#94a3b8',

    // Primary система
    primary: primaryBase,
    'primary-hover': primaryHover,
    'primary-active': primaryActive,
    'primary-contrast': isDark ? '#ffffff' : '#ffffff',

    // Системные цвета
    success: isDark ? '#10b981' : '#059669',
    'success-hover': isDark ? '#059669' : '#047857',
    warning: '#f59e0b',
    'warning-hover': '#d97706',
    error: '#ef4444',
    'error-hover': '#dc2626',
    info: primaryBase,
    'info-hover': primaryHover,

    // Акцент (вторичный)
    accent: shades[400] || shades[300] || shades[500] || '#8b5cf6',
    'accent-hover': shades[500] || shades[400] || shades[600] || '#7c3aed',

    // Disabled состояния
    disabled: isDark ? '#334155' : '#e2e8f0',
    'disabled-text': isDark ? '#64748b' : '#94a3b8',
  };

  const themeName = theme === 'auto' ? 'universal' : theme;
  const output = [
    `/* ==========================================================================`,
    ` * Semantic Color System (${themeName} theme)`,
    ` * Generated by tints.dev`,
    ` * Design-system ready color roles`,
    ` * ========================================================================== */`,
    ``,
    `:root {`
  ];

  Object.entries(semanticColors).forEach(([role, color]) => {
    output.push(`  --color-${role}: ${color};`);
  });

  output.push(`}`, ``);

  return output.join('\n');
};

export const generateDesignTokens = (palettes: PaletteConfig[], theme: 'light' | 'dark' | 'auto', currentMode: Mode): string => {
  if (!palettes || palettes.length === 0) {
    console.log('⚠️ No palettes for design tokens');
    return '';
  }

  const palette = palettes[0];
  if (!palette) {
    console.log('⚠️ No palette found for design tokens');
    return '';
  }

  const shades = palette.swatches.reduce((acc, swatch) => {
    if (![0, 1000].includes(swatch.stop)) {
      acc[swatch.stop] = createDisplayColor(swatch.hex, currentMode, true);
    }
    return acc;
  }, {} as Record<number, string>);

  const isDark = theme === 'dark';
  const themeName = theme === 'auto' ? 'universal' : theme;

  const tokens = {
    // Цветовая палитра
    palette: shades,

    // Семантические роли
    semantic: {
      background: isDark ? '#0f172a' : '#ffffff',
      surface: isDark ? '#1e293b' : '#f8fafc',
      'surface-hover': isDark ? '#334155' : '#f1f5f9',
      border: isDark ? '#334155' : '#e2e8f0',
      'border-hover': isDark ? '#475569' : '#cbd5e1',
      'text-primary': isDark ? '#f8fafc' : '#0f172a',
      'text-secondary': isDark ? '#94a3b8' : '#475569',
      'text-tertiary': isDark ? '#64748b' : '#64748b',
      primary: shades[500] || shades[600] || shades[700] || '#4f46e5',
      'primary-hover': shades[600] || shades[700] || shades[800] || '#4338ca',
      'primary-active': shades[700] || shades[800] || shades[900] || '#3730a3',
      success: isDark ? '#10b981' : '#059669',
      warning: '#f59e0b',
      error: '#ef4444',
      info: shades[500] || shades[600] || shades[700] || '#4f46e5',
    },

    // Компонентные токены
    components: {
      button: {
        primary: {
          background: shades[500] || shades[600] || shades[700] || '#4f46e5',
          hover: shades[600] || shades[700] || shades[800] || '#4338ca',
          active: shades[700] || shades[800] || shades[900] || '#3730a3',
          disabled: isDark ? '#334155' : '#e2e8f0',
          text: '#ffffff',
        },
        secondary: {
          background: isDark ? '#334155' : '#f8fafc',
          hover: isDark ? '#475569' : '#f1f5f9',
          active: isDark ? '#64748b' : '#e2e8f0',
          border: isDark ? '#475569' : '#cbd5e1',
          text: isDark ? '#f8fafc' : '#0f172a',
        }
      },
      input: {
        background: isDark ? '#1e293b' : '#ffffff',
        border: isDark ? '#334155' : '#e2e8f0',
        'border-focus': shades[500] || shades[600] || shades[700] || '#4f46e5',
        placeholder: isDark ? '#64748b' : '#94a3b8',
      }
    }
  };

  return JSON.stringify({
    name: `${palette.name} Design Tokens`,
    theme: themeName,
    version: '1.0.0',
    tokens
  }, null, 2);
};

// Create a test palette for testing purposes
export const createTestPalette = (): PaletteConfig => ({
  id: 'test-palette',
  name: 'Test Palette',
  value: '3B82F6',
  valueStop: 500,
  swatches: [
    { stop: 50, hex: '#eff6ff', h: 214, hScale: -50, s: 100, sScale: 0, l: 97 },
    { stop: 100, hex: '#dbeafe', h: 214, hScale: -50, s: 95, sScale: -5, l: 90 },
    { stop: 200, hex: '#bfdbfe', h: 214, hScale: -50, s: 91, sScale: -9, l: 80 },
    { stop: 300, hex: '#93c5fd', h: 214, hScale: -50, s: 86, sScale: -14, l: 70 },
    { stop: 400, hex: '#60a5fa', h: 214, hScale: -50, s: 82, sScale: -18, l: 60 },
    { stop: 500, hex: '#3b82f6', h: 214, hScale: -50, s: 78, sScale: -22, l: 50 },
    { stop: 600, hex: '#2563eb', h: 214, hScale: -50, s: 73, sScale: -27, l: 40 },
    { stop: 700, hex: '#1d4ed8', h: 214, hScale: -50, s: 69, sScale: -31, l: 30 },
    { stop: 800, hex: '#1e40af', h: 214, hScale: -50, s: 65, sScale: -35, l: 25 },
    { stop: 900, hex: '#1e3a8a', h: 214, hScale: -50, s: 61, sScale: -39, l: 20 },
    { stop: 950, hex: '#172554', h: 214, hScale: -50, s: 58, sScale: -42, l: 15 }
  ],
  h: 0,
  s: 0,
  lMin: 0,
  lMax: 100,
  colorMode: 'perceived',
  mode: 'oklch',
  stopSelection: 'auto',
  generationMode: 'curated',
  colorScheme: 'monochromatic',
  temperature: 'neutral',
  contrast: 'auto',
  accessibility: false,
  description: '',
  tags: []
});
